baseURL = "https://lopezalejandro.github.io/sysadmin/"
languageCode = "en-us"
defaultContentLanguage = "es"
title = "Bitácora de un Sysadmin"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = ""
enableGitInfo = true
publishDir = "docs"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Un sitio donde anotar los retos diarios, con los que se encuentra un sysadmin"
  homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/index"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/index"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
